export const drinkOptions = [
    {
        value:'vodka',
        label:'Vodka',
    },
    {
        value:'gin',
        label:'Gin',
    },
    {
        value:'whiskey',
        label:'Whiskey',
    },
    {
        value:'bourbon',
        label:'Bourbon',
    },
    {
        value:'tequila',
        label:'Tequila',
    },
    {
        value:'rum',
        label:'Rum',
    }
];